config/routes.rb
Eschool::Application.routes.draw do
  devise_for :users

  resources :subjects


  scope :controller => :sandbox, :as => :sandbox, :path => 'sandbox' do
    get '/' => :index, :as => :index
    post '/compile' => :compile, :as => :compile
  end

  # Must be the last route
  scope :controller => :home, :as => :main do
    get '/:url_indice' => :show_chapter, :as => :chapter
    get '/:url_indice/:chapter_nb(/:section_nb)' => :show_sections, :as => :sections
  end
  

  root :to => 'home#index'
end

app/models/.#chapter.rb
shant@shant-laptop.6190:1319490136

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :subject
  has_many :sections
  accepts_nested_attributes_for :sections, :reject_if => lambda { |a| a[:section_title].blank? }, :allow_destroy => true
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :chapter

  has_attached_file :video
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :chapters
  accepts_nested_attributes_for :chapters, :reject_if => lambda { |a| a[:chapter_title].blank? }, :allow_destroy => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  
  #, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  def admin?
    return self.admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  protected
  def admin_logged
    if current_user.present? and current_user.admin == true
      return true
    end
    redirect_to root_path
  end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # List subjects
  def index
    @subjects = Subject.all
  end
  
  def show_chapter
    @subject = Subject.first(:conditions => ['url_indice = ?', params[:url_indice]], :include => [:chapters])
    # @subject = Subject.where(:url_indice => params[:url_indice]).includes(:chapters, {:sections}).first
    print @subject
  end
  
  def show_sections
    @subject = Subject.first(:conditions => ['url_indice = ?', params[:url_indice]], :include => [:chapters])
    @chapter = @subject.chapters.where(:chapter_number => params[:chapter_nb]).first
    @section = @chapter.sections.where(:section_number => params[:section_nb]).first
  end

  def about
  end

end

app/controllers/sandbox_controller.rb
class SandboxController < ApplicationController
  
  def index
    
  end

  def compile
    # print @@ideone
    # #unless defined?(session[:ideone1])
    # #ideone = Ideone.new('tknew', '123456')
    # #end
    # token = @@ideone.create_submission(params[:code], 17)
    # print token
    # begin
    #   print "waiting data"
    #   data = @@ideone.submission_details(token)
    #   print data[:status]
    # end while data[:status] != "0"
    # print data
    # # @@ideone = nil
    # render :json => data
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_filter :admin_logged
  
  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subjects }
    end
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    @subject = Subject.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/new
  # GET /subjects/new.json
  def new
    @subject = Subject.new

    3.times do
      chapter = @subject.chapters.build
      2.times { 
        chapter.sections.build
      }
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/1/edit
  def edit
    @subject = Subject.find(params[:id])
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(params[:subject])

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render json: @subject, status: :created, location: @subject }
      else
        format.html { render action: "new" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subjects/1
  # PUT /subjects/1.json
  def update
    @subject = Subject.find(params[:id])

    respond_to do |format|
      if @subject.update_attributes(params[:subject])
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to subjects_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    if (text == nil)
      return ''
    end
    options = [:hard_wrap, :filter_html, :autolink, :no_intraemphasis, :fenced_code, :gh_blockcode]
    dt = Redcarpet.new(text, *options).to_html.html_safe
    content_tag(:div, dt, :id => 'markdown')
  end
  
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_part(this)")
  end

  def link_to_add_fields(name, f, association, css_class)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_form", :f => builder)
    end
    print fields
    link_to_function(name, "add_fields(this, '#{association}', '#{escape_javascript(fields)}')", :class => css_class)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sandbox_helper.rb
module SandboxHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/index.html.erb
<div class="main-page">
  <div class="page-header">
    <h1>What would you like to learn ? <small>by Web Lab</small></h1>
  </div>

  <% @subjects.each do |s| %>
    <section class="main-page-subjects-section" onclick="window.location = '<%= main_chapter_path(s.url_indice) %>';">
      <div class="page-header">
	<h2>
	  <%= s.subject_name %>
	</h2>
      </div>
      <div class="row">
	<div class="span16">
	  <p><%= s.resume %></p>
	  <% if s.url_indice.present? %>
	    <%= link_to 'Begin to learn', main_chapter_path(s.url_indice) %>
	  <% end %>
	</div>
      </div>
    </section>
  <% end %>
</div>

app/views/home/show_chapter.html.erb
<div class="chapters-page">
  <div class="page-header">
    <h1><%= @subject.subject_name %> <small>class</small></h1>
  </div>

  <% @subject.chapters.each do |c| %>
    <section class="chapter-descr">
      <div class="page-header-min">
	<h2>
	  <%= c.chapter_number.to_s + '. ' + c.chapter_title %>
	</h2>
      </div>
      <div class="row">
	
	<% c.sections.each do |s| %>
	  <div class="span3">
	    &nbsp;
	    <%- s.resume %>
	  </div>
	  <a href="<%= main_sections_path(params[:url_indice], c.chapter_number, s.section_number) %>">
	    <div class="span14 chapter-detail">
	      <div class="text-chapter">
		<%= s.section_number %>.
		<%= s.section_title %>
	      </div>
	      <div class="play-icon">
		<%= image_tag 'player_play.png' %>
	      </div>
	    </div>
	  </a>
	<% end %>
      </div>
    </section>
  <% end %>
</div>

app/views/home/show_sections.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag 'plugins/video.js' %>
  <%= javascript_include_tag 'show_sections.js' %>
<% end %>

<% content_for :stylesheets do %>
  <%= stylesheet_link_tag 'plugins/video-js.css' %>
<% end %>

<div class="show-sections">
  <div class="page-header">
    <h1><%= @section.section_number.to_s + '. ' + @section.section_title %> <small>&nbsp; Chapter <%= @chapter.chapter_number.to_s + ' - ' + @chapter.chapter_title + ' - ' + @subject.subject_name %> class</small></h1>
  </div>
  <div class="row">
    <div class="span11">

      <div class="video-js-box"> 
	<video id="example_video_1" class="video-js vjs-default-skin" controls="controls" preload="auto" width="640" height="450">
	       <!-- poster="http://localhost:3000/public/Simple-wallpaper-1-1366x768.jpg"> -->
	  <source src="<%= @section.video.url %>" type='video/mp4' />
	  <!-- <source src="http://video-js.zencoder.com/oceans-clip.webm" type='video/webm' /> -->
	</video>
      </div>
    </div>


    <!-- Video listing -->
    <div class="span5">
      <h3>Lessons listing</h3>
      <div class="video-listing">
	
	<ul>
	  <% @chapter.sections.each do |s| %>
	    
	    <li class="<%= s == @section ? 'selected' : '' %>" 
		onclick="window.location = '<%= main_sections_path(params[:url_indice], @chapter.chapter_number, s.section_number) %>'">
		<%= s.section_number %>. <%= s.section_title %>
	    </li>
	  <% end %>
	</ul>
      </div>
      
      <div class="begin-exercice btn primary">
	Begin exercices
      </div>

    </div>
  </div>

</div>

app/views/layouts/_footer.html.erb
<div id="web-lab">
  <span id="copyright">
    Copyright &copy; <%= Date.today.year %> - WebLab - Eschool
  </span>
  <span id="author">
    by <a target="_blank" href="http://apps.hemca.com" title="Strzelewicz Alexandre works">Strzelewicz Alexandre</a>
  </span>
</div>

app/views/layouts/_head.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="description" content="">
<meta name="author" content="">
<%- # Mobile viewport optimized: j.mp/bplateviewport -%>
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>Eschool :: <%= controller.action_name.titleize %></title>

<%# CSS : implied media="all" -%>
<%= stylesheet_link_tag 'application' %>
<%= yield :stylesheets %>

<%- # Uncomment if you are specifically targeting less enabled mobile browsers -%>
<%#= stylesheet_link_tag "handheld", :media => "handheld" %>

<%= csrf_meta_tag %>
<%= javascript_tag "window._token = '#{form_authenticity_token}'" %>

app/views/layouts/_javascript.html.erb
<%- # Javascript at the bottom for fast page loading -%>

<%= javascript_include_tag :application %>

<%= yield :javascripts %>

<%- # Fix any <img> or .png_bg background-images -%>

<%- # asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet -%>
<%- # change the UA-XXXXX-X to be your site's ID -%>
<%- if Rails.env.production? -%>
  <!-- <script> -->
  <!--   var _gaq = [['_setAccount', 'UA-XXXXX-X'], ['_trackPageview']]; -->
  <!--   (function(d, t) { -->
  <!--   var g = d.createElement(t), -->
  <!--   s = d.getElementsByTagName(t)[0]; -->
  <!--   g.async = true; -->
  <!--   g.src = ('https:' == location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js'; -->
  <!--   s.parentNode.insertBefore(g, s); -->
  <!--   })(document, 'script'); -->
  <!-- </script> -->
<%- end -%>

app/views/layouts/_menu.html.erb
<div class="topbar">
  <div class="topbar-inner">
    <div class="container">
      <a class="brand" href="#">ESchool</a>
      <%= render_navigation :level => 1 %>      
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <%= render :partial => 'layouts/head' %>
  </head>
  <body>
    <nav>
      <%= render :partial => 'layouts/menu' %>
    </nav>
    
    <header class="masthead">
      <!-- <div class="inner"> -->
      <!-- 	<div class="container"> -->
      <!-- 	  Eschool -->
      <!-- 	</div>	 -->
      <!-- </div> -->
    </header>
    
    <div class="container main">
      <%= yield %>
    </div>
    
    <footer class="footer">
      <div class="container">
	<%= render :partial => 'layouts/footer' %>
      </div>
    </footer>
        
    <%= render :partial => 'layouts/javascript' %>
  </body>
</html>

app/views/sandbox/compile.html.erb
<h1>Sandbox#compile</h1>
<p>Find me in app/views/sandbox/compile.html.erb</p>

app/views/sandbox/index.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag 'compile.js' %>
<% end %>


<div class="page-header">
  <h1>Ideone Sandbox <small>API</small></h1>
</div>

<section>
  <div class="page-header" id="title-compile">
    <h3>Code to compile</h3>
  </div>

  <div class="row">    
    <div class="span16">
      <textarea id="code-source" rows="7" style="width : 930px;">
      </textarea>
      <br/>
      <br/>
      <div class="btn primary" id="submit-code">
	Submit code
      </div>
    </div>
  </div>
</section>

<section>
  <div class="page-header">
    <h3>Result</h3>
  </div>

  <div class="row">    
    <div class="span16">
      <textarea rows="7" cols="30" style="width : 930px;">
      </textarea>
    </div>
  </div>
</section>

app/views/subjects/_chapter_form.html.erb
<!-- Inherit from .chapters -->
<div class="chapter-each">
  <div class="chapter-show-each" onclick="expand_chapter(this);">
    <div class="btn primary">
      Show chapter
    </div>
    <% if f.object.new_record? %>
      &nbsp;(New chapter)
    <% else %>
      &nbsp;&nbsp;&nbsp;<%= f.object.chapter_number.to_s + '. ' + f.object.chapter_title %>
    <% end %>

  </div>

  <div class="chapter-each-display">
    <!-- <div class="clearfix"> -->
    <!--   <%= f.label :enabled %> -->
    <!--   <div class="input"> -->
    <!-- 	<%= f.check_box :enabled %> -->
    <!--   </div> -->
    <!-- </div> -->
    
    <div class="clearfix">
      <%= f.label :chapter_title %>
      <div class="input">
	<%= f.text_field :chapter_title %>
      </div>
    </div>

    <!-- For URL mapping -->
    <%= f.hidden_field :chapter_number, :class => 'chapter_number_relative_id' %>
	
    <div class="clearfix">
      <%= f.label :resume %>
      <div class="input">
	<%= f.text_field :resume %>
      </div>
    </div>
    
    <div class="clearfix remove-chapter-link">
      <!-- Link to remove this chapter -->
      <%= link_to_remove_fields "X Remove chapter", f %>
    </div>
    
    <h3 class="sections-chapter-title">Sections</h3>
    <div class="sections">
      <%= link_to_add_fields "Add sections", f, :sections, 'add-sections-button' %>
      <%= f.fields_for :sections do |s| %>
	<%= render 'section_form', :f => s %>
      <% end %>
    </div>
    
  </div>
</div>

app/views/subjects/_form.html.erb
<% content_for :javascripts do %>
  <%= javascript_include_tag 'subject.js' %>
<% end %>


<div class="subject-management">

  <%= form_for(@subject) do |f| %>
    <% if @subject.errors.any? %>
      <div id="error_explanation">
	<h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

	<ul>
	  <% @subject.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
	  <% end %>
	</ul>
      </div>
    <% end %>

    <div class="subject row">

      <!-- Left part --> 
      <div class="span6">
	<div class="clearfix">
	  <%= f.label :subject_name %>
	  <div class="input">
	    <%= f.text_field :subject_name %>
	  </div>
	</div>
	
	<div class="clearfix">
	  <%= f.label :resume %>
	  <div class="input">
	    <%= f.text_area :resume, :size => '40x10'%>
	  </div>
	</div>
      </div>

      <!-- Right part --> 
      <div class="span6">
	<div class="clearfix">
	  <%= f.label :small_resume %>
	  <div class="input">
	    <%= f.text_field :small_resume %>
	  </div>
	</div>
	
	<div class="clearfix">
	  <%= f.label :url_indice %>
	  <div class="input">
	    <%= f.text_field :url_indice %>
	  </div>
	</div>	

	<% unless f.object.new_record? %>
	  <br/ >
	  <div class="clearfix">
	    <div class="input">
	      Chapters number : 
	      <%= @subject.chapters.count %>
	    </div>
	  </div>
	<% end %>

      </div>
      
      <!-- !.subject -->
    </div>

    <!-- Chapter part -->
    <div class="chapters">
      <%= link_to_add_fields "Add chapters", f, :chapters, 'add-chapters-button' %>
      <%= f.fields_for :chapters do |c| %>
	<%= render 'chapter_form', :f => c %>
      <% end %>    
    </div>
    
    
    
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
  
</div>

app/views/subjects/_section_form.html.erb
<div class="section-each">
  <div class="section-show-each" onclick="expand_section(this);">
    <div class="btn primary">
      Show section
    </div>
    <% if f.object.new_record? %>
      &nbsp;&nbsp;&nbsp;(New section)
    <% else %>
      &nbsp;&nbsp;&nbsp;<%= f.object.section_number.to_s + '. ' + f.object.section_title %>
    <% end %>
  </div>
  <div class="section-each-display">
    
    <!-- <div class="clearfix"> -->
    <!--   <%= f.label :enabled %> -->
    <!--   <div class="input"> -->
    <!-- 	<%= f.check_box :enabled %> -->
    <!--   </div> -->
    <!-- </div> -->
    
    <div class="clearfix">
      <%= f.label :section_title %>
      <div class="input">
	<%= f.text_field :section_title %>
      </div>
    </div>

    <!-- For url mapping -->
    <%= f.hidden_field :section_number, :class => 'section_number_relative_id' %>

    <div class="clearfix">
      <%= f.label :resume %>
      <div class="input">
	<%= f.text_field :resume %>
      </div>
    </div>

    <div class="clearfix">
      <%= f.label :video %>
      <div class="input">
	<%= f.file_field :video %> 
	<br/>
	<br/>
	<% if f.object.new_record? == false and f.object.video.present? %>
	  Vidéo already present : <strong><%= f.object.video.url.split('/')[-1] %></strong>
	<% end %>
      </div>
    </div>

    <div class="clearfix">
      <!-- Link to remove this chapter -->
      <%= link_to_remove_fields "Remove section", f %>
    </div>

  </div>

</div>

app/views/subjects/edit.html.erb
<h1>Editing lesson <%= @subject.subject_name %></h1>
<br/>
<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<h1>Listing subjects</h1>

<table>
  <tr>
    <th>Subject name</th>
    <th>Resume</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subjects.each do |subject| %>
  <tr>
    <td><%= subject.subject_name %></td>
    <td><%= subject.resume %></td>
    <td><%= link_to 'Show', subject %></td>
    <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
    <td><%= link_to 'Destroy', subject, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New subject</h1>

<%= render 'form' %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Subject name:</b>
  <%= @subject.subject_name %>
</p>

<p>
  <b>Resume:</b>
  <%= @subject.resume %>
</p>


<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>